"""
CountRight Single-File Bundle
============================

This file bundles all the code required to run `pipeline/run_countright.py`.
It is generated by collecting and concatenating the relevant modules from the
`make-it-count` project, so you can run the counting pipeline without relying
on the original multi-module layout.

Included modules (in dependency order):
  - counting_words_extract  (utils.counting_words_extract)
  - utils_masks             (pipeline.mask_extraction.utils_masks)
  - latent_noise_injection  (pipeline.module.latent_noise_injection)
  - generate_random_masks   (utils.generate_random_masks)
  - attention_processors    (pipeline.attention_processors)
  - attention_store_counting(pipeline.attention_store_counting)
  - loss                    (pipeline.module.loss)
  - self_counting_sdxl_pipeline (pipeline.self_counting_sdxl_pipeline)
  - attention_utils         (utils.attention_utils)
  - postprocess             (pipeline.mask_extraction.postprocess)
  - dbscan_mask_extract     (pipeline.mask_extraction.dbscan_mask_extract)
  - spatial_prior_predictor                (pipeline.mask_extraction.spatial_prior_predictor)
  - extract_mask            (pipeline.mask_extraction.extract_mask)
  - run_countright            (pipeline.run_countright)

Usage:
  python pipeline/module/one_file/run_countright_onefile.py \
      --prompt "A photo of six kittens sitting on a branch" \
      --seed 1 \
      --config pipeline/pipeline_config.yaml

Original files are NOT modified.
"""

import sys
import os
import io
import re
import math
import random
import inspect
import argparse
import json
from typing import Dict, List, Any, Callable, Optional, Tuple, Union
from collections import defaultdict
from pathlib import Path

import numpy as np
import yaml
import torch
import torch.nn.functional as F
import cv2
import spacy
import diffusers
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image, ImageOps
from tqdm import tqdm
from scipy.ndimage import label, find_objects, median_filter, zoom
from scipy.ndimage import zoom as scipy_zoom
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from skimage import filters
from IPython.display import display
from diffusers import StableDiffusionXLPipeline
from diffusers.utils.torch_utils import randn_tensor
from diffusers.pipelines.stable_diffusion_xl import StableDiffusionXLPipelineOutput
from diffusers.models.attention import Attention

matplotlib.use("Agg")


# ============================================================================
# 路径设置 (保持与原项目一致的相对路径查找)
# ============================================================================

# 找到 make-it-count 项目根目录 (此文件位于 pipeline/module/one_file/)
_THIS_FILE = os.path.abspath(__file__)
_PROJECT_ROOT = os.path.abspath(os.path.join(_THIS_FILE, "..", "..", ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)


# ============================================================================
# 1. counting_words_extract (utils.counting_words_extract)
# ============================================================================

start_token = "<|startoftext|>"
end_token = "<|endoftext|>"

pattern = re.compile(r'\b(one|two|three|four|five|six|seven|eight|nine|ten)\s(\w+)')


word2number = {'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
               'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10}


def find_nummod(sentences):
    results = []
    for sentence in sentences:
        match = pattern.search(sentence)
        if match:
            nummod = [match.group(1), match.group(2)]
            results.append(nummod)
    return results


def extract_attribution_indices_nummod(prompt, parser):
    doc = parser(prompt)
    subtrees = []
    modifiers = ["nummod"]
    for w in doc:
        if w.pos_ not in ["NOUN", "PROPN"] or w.dep_ in modifiers:
            continue
        subtree = []
        stack = []
        for child in w.children:
            if child.dep_ in modifiers:
                subtree.append(child)
                stack.extend(child.children)

        while stack:
            node = stack.pop()
            if node.dep_ in modifiers or node.dep_ == "conj":
                subtree.append(node)
                stack.extend(node.children)
        if subtree:
            subtree.append(w)
            subtrees.append(subtree)
    return subtrees


def get_indices(tokenizer, prompt: str) -> Dict[str, int]:
    """Utility function to list the indices of the tokens you wish to alter"""
    ids = tokenizer(prompt).input_ids
    indices = {
        i: tok
        for tok, i in zip(
            tokenizer.convert_ids_to_tokens(ids), range(len(ids))
        )
    }
    return indices


def align_wordpieces_indices(
        wordpieces2indices, start_idx, target_word
):
    """
    Aligns a `target_word` that contains more than one wordpiece (the first wordpiece is `start_idx`)
    """
    wp_indices = [start_idx]
    wp = wordpieces2indices[start_idx].replace("</w>", "")

    for wp_idx in range(start_idx + 1, len(wordpieces2indices)):
        if wp == target_word:
            break

        wp2 = wordpieces2indices[wp_idx].replace("</w>", "")
        if target_word.startswith(wp + wp2) and wp2 != target_word:
            wp += wordpieces2indices[wp_idx].replace("</w>", "")
            wp_indices.append(wp_idx)
        else:
            wp_indices = []
            break

    return wp_indices


# ============================================================================
# 2. utils_masks (pipeline.mask_extraction.utils_masks)
# ============================================================================

def from_channels(channels_mask):
    desired_number_of_clusters = channels_mask.size(0)
    channels_mask = channels_mask.flatten(start_dim=1)

    combined_mask = torch.zeros(1024, dtype=torch.float16)

    for i in range(desired_number_of_clusters):
        combined_mask[channels_mask[i] == 1] = i + 1

    combined_mask = combined_mask.view(32, 32)
    return combined_mask


def to_channels(masks):
    num_of_masks = int(masks.max().item())
    torch_object_masks = torch.zeros((num_of_masks, 32, 32), dtype=torch.float16)

    for i in range(num_of_masks):
        torch_object_masks[i][masks.detach() == i + 1] = 1

    return torch_object_masks


def remove_sparse_blobs(grid, min_blob_size=10):
    grid = grid.reshape(32, 32)
    unique_masks = np.unique(grid)
    unique_masks = unique_masks[unique_masks >= 0]
    updated_grid = grid.copy()
    for mask_id in unique_masks:
        binary_mask = (grid == mask_id)
        labeled_array, num_features = label(binary_mask)
        all_blobs_small = True
        for i in range(1, num_features + 1):
            blob_size = np.sum(labeled_array == i)
            if blob_size >= min_blob_size:
                all_blobs_small = False
                break
        if all_blobs_small:
            updated_grid[binary_mask] = -1

    unique_masks = np.unique(updated_grid)
    unique_masks = unique_masks[unique_masks >= 0]
    n_cluster_new = len(unique_masks)

    for i, cluster in enumerate(unique_masks):
        updated_grid[updated_grid == cluster] = i

    return torch.tensor(updated_grid).flatten(), n_cluster_new


def cut_bbox(boxes, image_size):
    fig, ax = plt.subplots()
    ax.set_xlim(0, image_size)
    ax.set_ylim(0, image_size)

    base_color = (0, 0, 0)
    for i, box in enumerate(boxes):
        color = base_color if i == 0 else np.random.rand(3, )
        rect = patches.Rectangle((box[0], box[1]), box[2] - box[0], box[3] - box[1], linewidth=1, edgecolor=color,
                                 facecolor='none')
        ax.add_patch(rect)

    relevant_boxes = boxes[1:]
    x1_all = min(box[0] for box in relevant_boxes)
    y1_all = min(box[1] for box in relevant_boxes)
    x2_all = max(box[2] for box in relevant_boxes)
    y2_all = max(box[3] for box in relevant_boxes)

    old_center = (image_size // 2, image_size // 2)

    dist_left = old_center[1] - x1_all
    dist_right = x2_all - old_center[1]
    dist_up = old_center[0] - y1_all
    dist_down = y2_all - old_center[0]
    print(f'dist_left: {dist_left}, dist_right: {dist_right}, dist_up: {dist_up}, dist_down: {dist_down}')

    final_rect_half_w = max(dist_left, dist_right, image_size // 4)
    final_rect_half_h = max(dist_up, dist_down, image_size // 4)
    final_half = max(final_rect_half_h, final_rect_half_w)
    final_rect = [image_size // 2 - final_half, image_size // 2 - final_half,
                  image_size // 2 + final_half, image_size // 2 + final_half]

    rect_all = patches.Rectangle((x1_all, y1_all), x2_all - x1_all, y2_all - y1_all, linewidth=2, edgecolor='blue',
                                 facecolor='none')
    ax.add_patch(rect_all)

    final_rect_patch = patches.Rectangle((final_rect[0], final_rect[1]), 2 * final_half, 2 * final_half,
                                         linewidth=1, edgecolor='red', facecolor='none')
    ax.add_patch(final_rect_patch)

    plt.gca().invert_yaxis()
    plt.axis('scaled')
    plt.title('Bounding Boxes')

    return relevant_boxes, final_rect


def get_bounding_boxes(masks):
    boxes = []
    for i in range(masks.shape[0]):
        mask = masks[i]
        nonzero = torch.nonzero(mask, as_tuple=False)
        if nonzero.size(0) == 0:
            continue
        ymin, xmin = torch.min(nonzero, dim=0).values
        ymax, xmax = torch.max(nonzero, dim=0).values
        boxes.append((xmin.item(), ymin.item(), xmax.item(), ymax.item()))
    return boxes


def find_tight_bbox(tensor):
    projection = torch.any(tensor > 0, dim=1)[0]
    non_zero_indices = projection.nonzero(as_tuple=True)
    y_min, y_max = non_zero_indices[0].min().item(), non_zero_indices[0].max().item()
    x_min, x_max = non_zero_indices[1].min().item(), non_zero_indices[1].max().item()

    return (y_min, x_min, y_max, x_max)


def make_square_crop(tensor, bbox):
    y_min, x_min, y_max, x_max = bbox
    height = y_max - y_min
    width = x_max - x_min

    square_size = max(height, width)

    padding_top = (square_size - height) // 2
    padding_bottom = square_size - height - padding_top
    padding_left = (square_size - width) // 2
    padding_right = square_size - width - padding_left

    cropped_tensor = tensor[..., y_min:y_max, x_min:x_max]

    square_tensor = F.pad(cropped_tensor, (padding_left, padding_right, padding_top, padding_bottom), "constant", 0)

    return square_tensor


# ============================================================================
# 3. latent_noise_injection (pipeline.module.latent_noise_injection)
# ============================================================================

ENABLE = True
NOISE_STRENGTH_BG = 0.7
FEATHER_RADIUS = 2
MASK_THRESHOLD = 0.5
GAUSSIAN_SIGMA_RATIO = 2.0


def apply_latent_partition(latents, masks):
    if not ENABLE:
        print("[LatentNoiseInjection] 模块已禁用，跳过")
        return latents

    if masks is None:
        print("[LatentNoiseInjection] 掩码为 None，跳过")
        return latents

    device = latents.device
    dtype = latents.dtype
    latent_h, latent_w = latents.shape[2], latents.shape[3]

    if isinstance(masks, np.ndarray):
        masks = torch.from_numpy(masks)
    masks = masks.to(device=device, dtype=torch.float32)

    if masks.dim() == 2:
        fg_mask = (masks > MASK_THRESHOLD).float()
    elif masks.dim() == 3:
        fg_mask = (masks > MASK_THRESHOLD).float().max(dim=0)[0]
    else:
        print(f"[LatentNoiseInjection] 不支持的掩码维度: {masks.dim()}，跳过")
        return latents

    mask_4d = fg_mask.unsqueeze(0).unsqueeze(0)
    mask_resized = F.interpolate(
        mask_4d,
        size=(latent_h, latent_w),
        mode='bilinear',
        align_corners=False,
    )
    mask_resized = torch.clamp(mask_resized, 0.0, 1.0)

    if FEATHER_RADIUS > 0:
        mask_resized = _gaussian_blur(mask_resized, FEATHER_RADIUS)

    strength_map = mask_resized * 1.0 + (1.0 - mask_resized) * NOISE_STRENGTH_BG
    strength_map = strength_map.to(device=device, dtype=dtype)

    latents_partitioned = latents * strength_map

    fg_ratio = (mask_resized > 0.5).float().mean().item()
    print(f"[LatentNoiseInjection] 噪声分区植入完成")
    print(f"  NOISE_STRENGTH_BG = {NOISE_STRENGTH_BG}")
    print(f"  FEATHER_RADIUS    = {FEATHER_RADIUS}")
    print(f"  前景区域占比      = {fg_ratio:.1%}")
    print(f"  strength_map: min={strength_map.min():.4f}, max={strength_map.max():.4f}, "
          f"mean={strength_map.mean():.4f}")
    print(f"  latents 变化: "
          f"原始 std={latents.std():.4f}, "
          f"分区后 std={latents_partitioned.std():.4f}")

    return latents_partitioned


def _gaussian_blur(mask: torch.Tensor, radius: int) -> torch.Tensor:
    sigma = max(radius / GAUSSIAN_SIGMA_RATIO, 0.1)
    kernel_size = 2 * radius + 1

    x = torch.arange(kernel_size, dtype=mask.dtype, device=mask.device) - radius
    kernel_1d = torch.exp(-0.5 * (x / sigma) ** 2)
    kernel_1d = kernel_1d / kernel_1d.sum()

    pad_h = radius
    mask_padded = F.pad(mask, (pad_h, pad_h, 0, 0), mode='reflect')
    mask_blurred = F.conv2d(mask_padded, kernel_1d.view(1, 1, 1, -1))

    pad_v = radius
    mask_padded = F.pad(mask_blurred, (0, 0, pad_v, pad_v), mode='reflect')
    mask_blurred = F.conv2d(mask_padded, kernel_1d.view(1, 1, -1, 1))

    return torch.clamp(mask_blurred, 0.0, 1.0)


# ============================================================================
# 4. generate_random_masks (utils.generate_random_masks)
# ============================================================================

def place_square(mask, k, value, padding, bounding_boxes):
    H, W = mask.shape

    for _ in range(10000):
        x = random.randint(0, W - k - 2 * padding)
        y = random.randint(0, H - k - 2 * padding)

        bounding_box = (x / W, y / H, (x + k + padding) / W, (y + k + padding) / H)

        if torch.all(mask[y:y + k + 2 * padding, x:x + k + 2 * padding] == 0):
            mask[y + padding:y + k + padding, x + padding:x + k + padding] = value
            bounding_boxes.append(bounding_box)
            return True
    return False


def generate_squares_mask(n, k, mask_size=(32, 32), padding=1, max_attempts=100):
    for attempt in range(max_attempts):
        mask = torch.zeros(mask_size, dtype=torch.int)
        bounding_boxes = []
        for value in range(1, n + 1):
            if not place_square(mask, k, value, padding, bounding_boxes):
                break
        else:
            return mask, bounding_boxes
    raise ValueError(f"Unable to place all squares after {max_attempts} attempts.")


def circles_do_not_overlap(center1, center2, min_distance):
    x1, y1 = center1
    x2, y2 = center2
    distance_squared = (x1 - x2) ** 2 + (y1 - y2) ** 2
    return distance_squared >= min_distance ** 2


def place_centers(n, radius, mask_size, padding):
    centers = []
    max_attempts = 10000
    min_distance = 2 * radius + 2 * padding

    for _ in range(n):
        for attempt in range(max_attempts):
            x_center = random.randint(radius + padding, mask_size[1] - radius - padding - 1)
            y_center = random.randint(radius + padding, mask_size[0] - radius - padding - 1)
            new_center = (x_center, y_center)

            if all(circles_do_not_overlap(center, new_center, min_distance) for center in centers):
                centers.append(new_center)
                break
        else:
            return None

    return centers


def draw_circles(mask, centers, radius, value_start=1):
    for i, (x_center, y_center) in enumerate(centers, start=value_start):
        for y in range(mask.size(0)):
            for x in range(mask.size(1)):
                if (x - x_center) ** 2 + (y - y_center) ** 2 <= radius ** 2:
                    mask[y, x] = i


def generate_circles_mask(n, radius, mask_size=(128, 128), padding=1, max_attempts=100):
    mask = torch.zeros(mask_size, dtype=torch.int)

    for attempt in range(max_attempts):
        centers = place_centers(n, radius, mask_size, padding)
        if centers is not None:
            draw_circles(mask, centers, radius)
            return mask

    return None


def show_mask(mask, save_path=None):
    """Display the mask with different colors for each square."""
    plt.figure(figsize=(8, 8))
    plt.imshow(mask, cmap='viridis', interpolation='nearest')
    plt.colorbar()
    plt.axis('off')

    if save_path is not None:
        plt.savefig(save_path, bbox_inches='tight')

    plt.show()


def show_mask_list(masks, titles=None, save_path=None):
    if titles is None:
        titles = [f"Mask {i + 1}" for i in range(len(masks))]

    fig, axs = plt.subplots(1, len(masks), figsize=(4 * len(masks), 4))
    for ax, mask, title in zip(axs, masks, titles):
        ax.imshow(mask, cmap='viridis', interpolation='nearest')
        ax.set_title(title)
        ax.axis('off')

    if save_path is not None:
        plt.savefig(save_path, bbox_inches='tight')

    plt.show()


def generate_random_masks_factory(shape='circle', number_clusters=2):
    if shape == 'circle':
        radius = int(np.sqrt(400 / (np.pi * number_clusters)))
        mask = generate_circles_mask(number_clusters, radius, mask_size=(32, 32), padding=1, max_attempts=200)

        if mask is None:
            radius -= 1
            mask = generate_circles_mask(number_clusters, radius, mask_size=(32, 32), padding=1, max_attempts=200)

        return mask
    elif shape == 'square':
        return generate_squares_mask(number_clusters, 8, mask_size=(32, 32), padding=1, max_attempts=200)


# ============================================================================
# 5. attention_processors (pipeline.attention_processors)
# ============================================================================

class CountingProcessor:
    def __init__(self, attnstore, place_in_unet):
        super().__init__()
        self.attnstore = attnstore
        self.place_in_unet = place_in_unet
        self.curr_step = 0

    def __call__(self, attn: Attention, hidden_states, encoder_hidden_states=None, attention_mask=None, **kwargs):
        batch_size, sequence_length, _ = hidden_states.shape
        attention_mask = attn.prepare_attention_mask(attention_mask, sequence_length, batch_size)

        query = attn.to_q(hidden_states)

        is_cross = encoder_hidden_states is not None
        encoder_hidden_states = encoder_hidden_states if encoder_hidden_states is not None else hidden_states
        key = attn.to_k(encoder_hidden_states)
        value = attn.to_v(encoder_hidden_states)

        query = attn.head_to_batch_dim(query)
        key = attn.head_to_batch_dim(key)
        value = attn.head_to_batch_dim(value)

        attention_probs = attn.get_attention_scores(query, key, attention_mask)

        self.attnstore(attention_probs, is_cross, self.place_in_unet, attn.heads)

        attn_dim = self.attnstore.attn_res[0]
        if self.attnstore.loss and self.attnstore.masking_dict['enable'] and \
            (attention_probs.shape[0] == 40 and attention_probs.shape[2] == attn_dim ** 2
             and self.attnstore.masking_dict['start_step'] <= self.attnstore.curr_step_index <=
             self.attnstore.masking_dict['end_step']
             and 'up' in self.place_in_unet):
            max_blob_index = torch.max(self.attnstore.desired_mask).int().item()
            attention_probs = attention_probs.view(40, attn_dim, attn_dim, attn_dim ** 2)

            blob_coordinates = torch.zeros((attn_dim, attn_dim), device=attention_probs.device)

            for j in range(0, max_blob_index + 1):
                current_blob_mask = self.attnstore.desired_mask == j
                indices = current_blob_mask.nonzero(as_tuple=False)
                if len(indices) > 0:
                    blob_coordinates[indices[:, 0], indices[:, 1]] = 1

            blob_coordinates_flat = blob_coordinates.view(-1).bool()

            blobs_indexes = (self.attnstore.desired_mask == 0).nonzero(as_tuple=False)

            for idx in blobs_indexes:
                x, y = idx[0], idx[1]
                attention_probs[:, x, y, blob_coordinates_flat] = 0

            attention_probs = attention_probs.reshape(40, attn_dim ** 2, attn_dim ** 2)

        hidden_states = torch.bmm(attention_probs, value)
        hidden_states = attn.batch_to_head_dim(hidden_states)

        hidden_states = attn.to_out[0](hidden_states)
        hidden_states = attn.to_out[1](hidden_states)

        return hidden_states


# ============================================================================
# 6. attention_store_counting (pipeline.attention_store_counting)
# ============================================================================

class CrossAndSelfAttentionStore:
    @staticmethod
    def get_empty_step_store(save_timesteps=None):
        d = defaultdict(list)
        for t in save_timesteps:
            d[t] = {}
        return d

    @staticmethod
    def get_empty_store():
        return {}

    def __init__(self, attn_res, save_timesteps, loss, masking_dict, desired_mask, object_token_idx):
        self.num_att_layers = -1
        self.cur_att_layer = 0
        self.curr_step_index = 0
        self.count_ts = 0

        if save_timesteps == "all":
            self.save_timesteps = list(range(50))
        else:
            self.save_timesteps = save_timesteps

        self.attn_res = (attn_res, attn_res)
        self.loss = loss
        self.masking_dict = masking_dict

        self.desired_mask = desired_mask
        self.object_token_idx = object_token_idx

        if desired_mask is not None:
            self.channels_desired_mask = to_channels(self.desired_mask).to(device=self.desired_mask.device).bool()

        self.cross_step_store = self.get_empty_step_store(self.save_timesteps)
        self.self_step_store = self.get_empty_step_store(self.save_timesteps)

        self.cross_attention_store = self.get_empty_store()
        self.self_attention_store = self.get_empty_store()

        self.all_cross_attention = {}
        self.all_self_attention = {}

    def __call__(self, attn, is_cross: bool, place_in_unet: str, attn_heads):
        if (self.save_timesteps is None) or (self.curr_step_index in self.save_timesteps) or self.loss:
            if (attn.shape[1] == np.prod(self.attn_res)) and (self.cur_att_layer >= 0):

                if (not self.loss) and (is_cross):
                    guided_attn = attn[attn.size(0) // 2:]
                else:
                    guided_attn = attn

                if is_cross:
                    guided_attn = guided_attn.reshape(
                        [guided_attn.shape[0] // attn_heads, attn_heads, *guided_attn.shape[1:]]).mean(dim=1)

                    self.cross_attention_store[place_in_unet] = guided_attn
                    if self.curr_step_index in self.save_timesteps:
                        self.cross_step_store[self.curr_step_index][place_in_unet] = guided_attn
                else:
                    guided_attn = guided_attn.reshape(
                        [guided_attn.shape[0] // attn_heads, attn_heads, *guided_attn.shape[1:]]).mean(dim=1)

                    self.self_attention_store[place_in_unet] = guided_attn
                    if self.curr_step_index in self.save_timesteps:
                        self.self_step_store[self.curr_step_index][place_in_unet] = guided_attn

        self.cur_att_layer += 1
        if self.cur_att_layer == self.num_att_layers:
            self.cur_att_layer = 0
            self.between_steps()

    def between_steps(self):
        self.all_cross_attention = self.cross_attention_store
        self.cross_attention_store = self.get_empty_store()
        self.all_self_attention = self.self_attention_store
        self.self_attention_store = self.get_empty_store()

    def aggregate_attention(self, from_where: List[str], get_cross=True) -> torch.Tensor:
        out = []
        if get_cross:
            attention_maps = self.all_cross_attention
        else:
            attention_maps = self.all_self_attention

        for layer, curr_map in attention_maps.items():
            if any([x in layer for x in from_where]):
                curr_map_reshape = curr_map.reshape(-1, self.attn_res[0], self.attn_res[1], curr_map.shape[-1])
                out.append(curr_map_reshape)

        out = torch.cat(out, dim=0)
        out = out.sum(0) / out.shape[0]
        return out


# ============================================================================
# 7. loss (pipeline.module.loss)
# ============================================================================

GAUSSIAN_PEAK_VALUE = 1.0
GAUSSIAN_SIGMA_SCALE = 3.0
BCE_MIN_VALUE = 0.05
BCE_MAX_VALUE = 0.95
NUMERICAL_STABILITY_EPS = 1e-8
COVARIANCE_REG_EPS = 1e-5
MIN_FOREGROUND_PIXELS = 3


def get_gaussian_target(mask, peak_value=GAUSSIAN_PEAK_VALUE, sigma_scale=GAUSSIAN_SIGMA_SCALE):
    masks = mask.unsqueeze(0) if mask.dim() == 2 else mask
    target = torch.zeros_like(masks, dtype=torch.float32)

    B, H, W = masks.shape
    device = masks.device

    y_grid = torch.arange(H, device=device, dtype=torch.float32)
    x_grid = torch.arange(W, device=device, dtype=torch.float32)
    yy, xx = torch.meshgrid(y_grid, x_grid, indexing='ij')
    grid = torch.stack([xx, yy], dim=-1)

    for i in range(B):
        m = masks[i]
        indices = torch.nonzero(m)
        if len(indices) < MIN_FOREGROUND_PIXELS:
            continue

        pts = torch.stack([indices[:, 1], indices[:, 0]], dim=-1).float()

        mu = torch.mean(pts, dim=0)

        pts_centered = pts - mu

        N = pts.shape[0]
        cov_matrix = torch.matmul(pts_centered.T, pts_centered) / (N - 1)

        cov_matrix += torch.eye(2, device=device) * COVARIANCE_REG_EPS

        cov_inv = torch.linalg.inv(cov_matrix)

        grid_centered = grid - mu

        mahalanobis_dist_sq = torch.einsum(
            'hwi,ij,hwj->hw',
            grid_centered,
            cov_inv,
            grid_centered
        )

        gaussian = peak_value * torch.exp(-0.5 * (1.0 / (sigma_scale ** 2)) * mahalanobis_dist_sq)

        target[i] = gaussian * m.float()

    return target.squeeze(0) if mask.dim() == 2 else target


def object_layout_loss(object_attention_map, config, desired_mask, attnstore):
    foreground_mask = (desired_mask != 0).to(dtype=object_attention_map.dtype)
    loss_cross = 0

    if config['cross_loss_step_range'][0] <= attnstore.curr_step_index <= config['cross_loss_step_range'][1] \
            and config['cross_loss_weight'] > 0:

        attn_min = torch.min(object_attention_map)
        attn_max = torch.max(object_attention_map)
        norm_attn_map = (object_attention_map - attn_min) / (attn_max - attn_min + NUMERICAL_STABILITY_EPS)

        if config.get('cross_attn_loss_type') == 'gaussian_dice':
            peak_value = config.get('gaussian_peak_value', GAUSSIAN_PEAK_VALUE)
            sigma_scale = config.get('gaussian_sigma_scale', GAUSSIAN_SIGMA_SCALE)

            target_gaussian = get_gaussian_target(foreground_mask, peak_value, sigma_scale)
            target_gaussian = target_gaussian.to(device=norm_attn_map.device, dtype=norm_attn_map.dtype)

            A = norm_attn_map.flatten(start_dim=-2)
            T = target_gaussian.flatten(start_dim=-2)

            intersection = torch.sum(A * T, dim=-1)

            union = torch.sum(A * A, dim=-1) + torch.sum(T * T, dim=-1)

            dice_loss = 1.0 - (2.0 * intersection + NUMERICAL_STABILITY_EPS) / (union + NUMERICAL_STABILITY_EPS)

            loss_cross = dice_loss.mean()

        elif config['cross_attn_loss_type'] == 'gaussian_mse':
            target_gaussian = get_gaussian_target(foreground_mask, GAUSSIAN_PEAK_VALUE, GAUSSIAN_SIGMA_SCALE)
            target_gaussian = target_gaussian.to(device=norm_attn_map.device, dtype=norm_attn_map.dtype)
            loss_cross = F.mse_loss(norm_attn_map, target_gaussian)

        elif config['cross_attn_loss_type'] == 'bce_logits':
            loss_cross = F.binary_cross_entropy_with_logits(
                object_attention_map,
                foreground_mask,
                pos_weight=torch.tensor(config['cross_attn_bce_pos_wt']).to(object_attention_map.device)
            )
        elif config['cross_attn_loss_type'] == 'bce':
            norm_attn_map_scaled = norm_attn_map * (BCE_MAX_VALUE - BCE_MIN_VALUE) + BCE_MIN_VALUE
            loss_cross = F.binary_cross_entropy(norm_attn_map_scaled, foreground_mask)

    loss = config['cross_loss_weight'] * loss_cross
    return loss


# ============================================================================
# 8. self_counting_sdxl_pipeline (pipeline.self_counting_sdxl_pipeline)
# ============================================================================

def rescale_noise_cfg(noise_cfg, noise_pred_text, guidance_rescale=0.0):
    std_text = noise_pred_text.std(dim=list(range(1, noise_pred_text.ndim)), keepdim=True)
    std_cfg = noise_cfg.std(dim=list(range(1, noise_cfg.ndim)), keepdim=True)
    noise_pred_rescaled = noise_cfg * (std_text / std_cfg)
    noise_cfg = guidance_rescale * noise_pred_rescaled + (1 - guidance_rescale) * noise_cfg
    return noise_cfg


def retrieve_timesteps(
        scheduler,
        num_inference_steps: Optional[int] = None,
        device: Optional[Union[str, torch.device]] = None,
        timesteps: Optional[List[int]] = None,
        **kwargs,
):
    if timesteps is not None:
        accepts_timesteps = "timesteps" in set(inspect.signature(scheduler.set_timesteps).parameters.keys())
        if not accepts_timesteps:
            raise ValueError(
                f"The current scheduler class {scheduler.__class__}'s `set_timesteps` does not support custom"
                f" timestep schedules. Please check whether you are using the correct scheduler."
            )
        scheduler.set_timesteps(timesteps=timesteps, device=device, **kwargs)
        timesteps = scheduler.timesteps
        num_inference_steps = len(timesteps)
    else:
        scheduler.set_timesteps(num_inference_steps, device=device, **kwargs)
        timesteps = scheduler.timesteps
    return timesteps, num_inference_steps


class SelfCountingSDXLPipeline(StableDiffusionXLPipeline):
    def _extract_object_name(self, prompt):
        pairs = extract_attribution_indices_nummod(prompt, self.parser)
        paired_indices = self._align_indices(prompt, pairs)
        return paired_indices, pairs

    def _align_indices(self, prompt, spacy_pairs, start_token_="<|startoftext|>", end_token_="<|endoftext|>"):
        wordpieces2indices = get_indices(self.tokenizer, prompt)
        paired_indices = []
        collected_spacy_indices = set()

        for pair in spacy_pairs:
            curr_collected_wp_indices = []
            for member in pair:
                for idx, wp in wordpieces2indices.items():
                    if wp in [start_token_, end_token_]:
                        continue

                    wp = wp.replace("</w>", "")
                    if member.text == wp:
                        if idx not in curr_collected_wp_indices and idx not in collected_spacy_indices:
                            curr_collected_wp_indices.append(idx)
                            break
                    elif member.text.startswith(wp) and wp != member.text:
                        wp_indices = align_wordpieces_indices(
                            wordpieces2indices, idx, member.text
                        )
                        if wp_indices and (wp_indices not in curr_collected_wp_indices) and all(
                                [wp_idx not in collected_spacy_indices for wp_idx in wp_indices]):
                            curr_collected_wp_indices.append(wp_indices)
                            break

            for collected_idx in curr_collected_wp_indices:
                if isinstance(collected_idx, list):
                    for idx in collected_idx:
                        collected_spacy_indices.add(idx)
                else:
                    collected_spacy_indices.add(collected_idx)

            paired_indices.append(curr_collected_wp_indices)

        return paired_indices

    def register_attention_control(self):
        attn_procs = {}
        cross_att_count = 0
        for i, name in enumerate(self.unet.attn_processors.keys()):
            if name.startswith("mid_block"):
                place_in_unet = f"mid_{i}"
            elif name.startswith("up_blocks"):
                place_in_unet = f"up_{i}"
            elif name.startswith("down_blocks"):
                place_in_unet = f"down_{i}"
            else:
                continue

            cross_att_count += 1
            attn_procs[name] = CountingProcessor(
                attnstore=self.attention_store, place_in_unet=place_in_unet
            )

        self.unet.set_attn_processor(attn_procs)
        self.attention_store.num_att_layers = cross_att_count

    def compute_loss(self, object_attention_map):
        loss = object_layout_loss(object_attention_map, self.counting_config["loss"], desired_mask=self.desired_mask,
                                  attnstore=self.attention_store)
        return loss

    def loss_and_plot(self, object_token_idx, i):
        cross_attention_maps = self.attention_store.aggregate_attention(
            from_where=self.counting_config["loss"]["cross_attention_agg_layers"], get_cross=True)
        cross_attention_maps = cross_attention_maps.permute(2, 0, 1)
        object_attention_map = cross_attention_maps[object_token_idx]

        loss = self.compute_loss(object_attention_map)

        return loss

    def perform_iterative_refinement_step(self, loss, latents, curr_prompt_embeds,
                                          timestep_cond, added_cond_kwargs, t,
                                          threshold, object_token_idx,
                                          i, step_size, max_refinement_steps=20):
        iteration = 0
        target_loss = threshold

        while loss > target_loss:
            iteration += 1

            latents = latents.clone().detach().requires_grad_(True)
            _ = self.unet(
                latents,
                t,
                encoder_hidden_states=curr_prompt_embeds,
                timestep_cond=timestep_cond,
                cross_attention_kwargs=self.cross_attention_kwargs,
                added_cond_kwargs=added_cond_kwargs,
                return_dict=False,
            )[0]
            self.unet.zero_grad()

            loss = self.loss_and_plot(object_token_idx, i)

            if loss != 0:
                latents = self.update_latent(
                    latents=latents,
                    loss=loss,
                    step_size=step_size,
                )

                print(f"Iteration {i} refinment {iteration} | Loss: {loss:0.4f}")

            if iteration >= max_refinement_steps:
                print(f"Exceeded max number of iterations ({max_refinement_steps})! ")
                break

        latents = latents.clone().detach().requires_grad_(True)

        _ = self.unet(
            latents,
            t,
            encoder_hidden_states=curr_prompt_embeds,
            timestep_cond=timestep_cond,
            cross_attention_kwargs=self.cross_attention_kwargs,
            added_cond_kwargs=added_cond_kwargs,
            return_dict=False,
        )[0]
        self.unet.zero_grad()

        loss = self.loss_and_plot(object_token_idx, i)

        print(f"Iteration {i} refinment finished | Loss: {loss:0.4f}")
        return loss, latents

    def update_latent(self, latents, loss, step_size):
        grad = torch.autograd.grad(loss, latents, create_graph=False)[0]
        latents = latents - step_size * grad
        return latents

    @torch.no_grad()
    def __call__(
            self,
            prompt: Union[str, List[str]] = None,
            prompt_2: Optional[Union[str, List[str]]] = None,
            height: Optional[int] = None,
            width: Optional[int] = None,
            num_inference_steps: int = 50,
            timesteps: List[int] = None,
            denoising_end: Optional[float] = None,
            guidance_scale: float = 5.0,
            negative_prompt: Optional[Union[str, List[str]]] = None,
            negative_prompt_2: Optional[Union[str, List[str]]] = None,
            num_images_per_prompt: Optional[int] = 1,
            eta: float = 0.0,
            generator: Optional[Union[torch.Generator, List[torch.Generator]]] = None,
            latents: Optional[torch.FloatTensor] = None,
            prompt_embeds: Optional[torch.FloatTensor] = None,
            negative_prompt_embeds: Optional[torch.FloatTensor] = None,
            pooled_prompt_embeds: Optional[torch.FloatTensor] = None,
            negative_pooled_prompt_embeds: Optional[torch.FloatTensor] = None,
            output_type: Optional[str] = "pil",
            return_dict: bool = True,
            cross_attention_kwargs: Optional[Dict[str, Any]] = None,
            guidance_rescale: float = 0.0,
            original_size: Optional[Tuple[int, int]] = None,
            crops_coords_top_left: Tuple[int, int] = (0, 0),
            target_size: Optional[Tuple[int, int]] = None,
            negative_original_size: Optional[Tuple[int, int]] = None,
            negative_crops_coords_top_left: Tuple[int, int] = (0, 0),
            negative_target_size: Optional[Tuple[int, int]] = None,
            clip_skip: Optional[int] = None,
            callback_on_step_end: Optional[Callable[[int, int, Dict], None]] = None,
            callback_on_step_end_tensor_inputs: List[str] = ["latents"],

            perform_counting=False,
            desired_mask=None,

            **kwargs,
    ):
        callback = kwargs.pop("callback", None)
        callback_steps = kwargs.pop("callback_steps", None)

        height = height or self.default_sample_size * self.vae_scale_factor
        width = width or self.default_sample_size * self.vae_scale_factor

        original_size = original_size or (height, width)
        target_size = target_size or (height, width)

        self.parser = spacy.load("en_core_web_sm")

        self.check_inputs(
            prompt,
            prompt_2,
            height,
            width,
            callback_steps,
            negative_prompt,
            negative_prompt_2,
            prompt_embeds,
            negative_prompt_embeds,
            pooled_prompt_embeds,
            negative_pooled_prompt_embeds,
            callback_on_step_end_tensor_inputs,
        )

        self._guidance_scale = guidance_scale
        self._guidance_rescale = guidance_rescale
        self._clip_skip = clip_skip
        self._cross_attention_kwargs = cross_attention_kwargs
        self._denoising_end = denoising_end
        self._interrupt = False

        if prompt is not None and isinstance(prompt, str):
            batch_size = 1
        elif prompt is not None and isinstance(prompt, list):
            batch_size = len(prompt)
        else:
            batch_size = prompt_embeds.shape[0]

        device = self._execution_device

        lora_scale = (
            self.cross_attention_kwargs.get("scale", None) if self.cross_attention_kwargs is not None else None
        )

        (
            prompt_embeds,
            negative_prompt_embeds,
            pooled_prompt_embeds,
            negative_pooled_prompt_embeds,
        ) = self.encode_prompt(
            prompt=prompt,
            prompt_2=prompt_2,
            device=device,
            num_images_per_prompt=num_images_per_prompt,
            do_classifier_free_guidance=self.do_classifier_free_guidance,
            negative_prompt=negative_prompt,
            negative_prompt_2=negative_prompt_2,
            prompt_embeds=prompt_embeds,
            negative_prompt_embeds=negative_prompt_embeds,
            pooled_prompt_embeds=pooled_prompt_embeds,
            negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
            lora_scale=lora_scale,
            clip_skip=self.clip_skip,
        )

        timesteps, num_inference_steps = retrieve_timesteps(self.scheduler, num_inference_steps, device, timesteps)

        num_channels_latents = self.unet.config.in_channels
        latents = self.prepare_latents(
            batch_size * num_images_per_prompt,
            num_channels_latents,
            height,
            width,
            prompt_embeds.dtype,
            device,
            generator,
            latents,
        )

        extra_step_kwargs = self.prepare_extra_step_kwargs(generator, eta)
        paired_indices, pairs = self._extract_object_name(prompt[0])
        object_token_idx = paired_indices[0][1]
        object_token_idx = object_token_idx[-1] if isinstance(object_token_idx, list) else object_token_idx

        self.desired_mask = None
        if perform_counting:
            self.desired_mask = torch.tensor(desired_mask, device=device, dtype=latents.dtype)

        add_text_embeds = pooled_prompt_embeds
        if self.text_encoder_2 is None:
            text_encoder_projection_dim = int(pooled_prompt_embeds.shape[-1])
        else:
            text_encoder_projection_dim = self.text_encoder_2.config.projection_dim

        add_time_ids = self._get_add_time_ids(
            original_size,
            crops_coords_top_left,
            target_size,
            dtype=prompt_embeds.dtype,
            text_encoder_projection_dim=text_encoder_projection_dim,
        )
        if negative_original_size is not None and negative_target_size is not None:
            negative_add_time_ids = self._get_add_time_ids(
                negative_original_size,
                negative_crops_coords_top_left,
                negative_target_size,
                dtype=prompt_embeds.dtype,
                text_encoder_projection_dim=text_encoder_projection_dim,
            )
        else:
            negative_add_time_ids = add_time_ids

        if self.do_classifier_free_guidance:
            prompt_embeds = torch.cat([negative_prompt_embeds, prompt_embeds], dim=0)
            add_text_embeds = torch.cat([negative_pooled_prompt_embeds, add_text_embeds], dim=0)
            add_time_ids = torch.cat([negative_add_time_ids, add_time_ids], dim=0)

        prompt_embeds = prompt_embeds.to(device)
        add_text_embeds = add_text_embeds.to(device)
        add_time_ids = add_time_ids.to(device).repeat(batch_size * num_images_per_prompt, 1)

        counting_prompt_embeds = (
            prompt_embeds[prompt_embeds.size(0) // 2:] if self.do_classifier_free_guidance else prompt_embeds)
        counting_add_text_embeds = (
            add_text_embeds[add_text_embeds.size(0) // 2:] if self.do_classifier_free_guidance else add_text_embeds)
        counting_add_time_ids = (
            add_time_ids[add_time_ids.size(0) // 2:] if self.do_classifier_free_guidance else add_time_ids)

        scale_ranges = self.counting_config['loss']['scale_ranges']
        scale_range = [np.linspace(x[0], x[1], x[2]) for x in scale_ranges]
        scale_range = np.concatenate(scale_range)
        step_size = self.counting_config['loss']['scale_factor'] * np.sqrt(scale_range)

        thresholds = self.counting_config['loss']['thresholds']

        num_warmup_steps = max(len(timesteps) - num_inference_steps * self.scheduler.order, 0)

        if (
                self.denoising_end is not None
                and isinstance(self.denoising_end, float)
                and 0 < self.denoising_end < 1
        ):
            discrete_timestep_cutoff = int(
                round(
                    self.scheduler.config.num_train_timesteps
                    - (self.denoising_end * self.scheduler.config.num_train_timesteps)
                )
            )
            num_inference_steps = len(list(filter(lambda ts: ts >= discrete_timestep_cutoff, timesteps)))
            timesteps = timesteps[:num_inference_steps]

        self.attention_store = CrossAndSelfAttentionStore(
            self.counting_config["attention_store"]["cross_attention_dim"],
            self.counting_config["attention_store"]["save_timesteps"],
            loss=perform_counting, masking_dict=self.counting_config["self_attention_masking"],
            desired_mask=self.desired_mask, object_token_idx=object_token_idx)
        self.register_attention_control()

        torch.cuda.empty_cache()

        sg_t_start = self.counting_config['loss']['sg_t_start']
        sg_t_end = self.counting_config['loss']['sg_t_end']
        if sg_t_end < 0: sg_t_end = len(timesteps)

        timestep_cond = None
        if self.unet.config.time_cond_proj_dim is not None:
            guidance_scale_tensor = torch.tensor(self.guidance_scale - 1).repeat(batch_size * num_images_per_prompt)
            timestep_cond = self.get_guidance_scale_embedding(
                guidance_scale_tensor, embedding_dim=self.unet.config.time_cond_proj_dim
            ).to(device=device, dtype=latents.dtype)

        self._num_timesteps = len(timesteps)
        with self.progress_bar(total=num_inference_steps) as progress_bar:
            for i, t in enumerate(timesteps):
                self.attention_store.curr_step_index = i
                if self.interrupt:
                    continue

                if perform_counting and sg_t_start <= i < sg_t_end:
                    with torch.enable_grad():
                        latents = latents.clone().detach().requires_grad_(True)
                        updated_latents = []

                        for latent, index, curr_prompt_embeds, curr_add_text_embeds, curr_add_time_ids in \
                                zip(latents, paired_indices, counting_prompt_embeds, counting_add_text_embeds,
                                    counting_add_time_ids):
                            latent = latent.unsqueeze(0)
                            curr_prompt_embeds = curr_prompt_embeds.unsqueeze(0)
                            curr_add_text_embeds = curr_add_text_embeds.unsqueeze(0)
                            curr_add_time_ids = curr_add_time_ids.unsqueeze(0)

                            added_cond_kwargs = {"text_embeds": curr_add_text_embeds, "time_ids": curr_add_time_ids}
                            _ = self.unet(
                                latent,
                                t,
                                encoder_hidden_states=curr_prompt_embeds,
                                timestep_cond=timestep_cond,
                                cross_attention_kwargs=self.cross_attention_kwargs,
                                added_cond_kwargs=added_cond_kwargs,
                                return_dict=False,
                            )[0]
                            self.unet.zero_grad()

                            loss = self.loss_and_plot(object_token_idx, i)

                            if i in thresholds.keys() and loss > thresholds[i]:
                                print(
                                    f"Iteration {i} | Entering refinement | Initial Loss: {loss:0.4f} | Threshold: {thresholds[i]:0.4f}")
                                loss, latent = self.perform_iterative_refinement_step(
                                    loss, latent, curr_prompt_embeds, timestep_cond, added_cond_kwargs, t,
                                    thresholds[i], object_token_idx, i, step_size[i],
                                    max_refinement_steps=self.counting_config["loss"]["max_refinement_steps"]
                                )

                            if loss != 0:
                                latent = self.update_latent(
                                    latents=latent,
                                    loss=loss,
                                    step_size=step_size[i],
                                )

                            print(f"Iteration {i} | Loss: {loss:0.4f}")
                            updated_latents.append(latent)

                    latents = torch.cat(updated_latents, dim=0)

                latent_model_input = torch.cat([latents] * 2) if self.do_classifier_free_guidance else latents

                latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)

                added_cond_kwargs = {"text_embeds": add_text_embeds, "time_ids": add_time_ids}
                noise_pred = self.unet(
                    latent_model_input,
                    t,
                    encoder_hidden_states=prompt_embeds,
                    timestep_cond=timestep_cond,
                    cross_attention_kwargs=self.cross_attention_kwargs,
                    added_cond_kwargs=added_cond_kwargs,
                    return_dict=False,
                )[0]

                if self.do_classifier_free_guidance:
                    noise_pred_uncond, noise_pred_text = noise_pred.chunk(2)
                    noise_pred = noise_pred_uncond + self.guidance_scale * (noise_pred_text - noise_pred_uncond)

                if self.do_classifier_free_guidance and self.guidance_rescale > 0.0:
                    noise_pred = rescale_noise_cfg(noise_pred, noise_pred_text, guidance_rescale=self.guidance_rescale)

                latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs, return_dict=False)[0]

                if callback_on_step_end is not None:
                    callback_kwargs = {}
                    for k in callback_on_step_end_tensor_inputs:
                        callback_kwargs[k] = locals()[k]
                    callback_outputs = callback_on_step_end(self, i, t, callback_kwargs)

                    latents = callback_outputs.pop("latents", latents)
                    prompt_embeds = callback_outputs.pop("prompt_embeds", prompt_embeds)
                    negative_prompt_embeds = callback_outputs.pop("negative_prompt_embeds", negative_prompt_embeds)
                    add_text_embeds = callback_outputs.pop("add_text_embeds", add_text_embeds)
                    negative_pooled_prompt_embeds = callback_outputs.pop(
                        "negative_pooled_prompt_embeds", negative_pooled_prompt_embeds
                    )
                    add_time_ids = callback_outputs.pop("add_time_ids", add_time_ids)
                    negative_add_time_ids = callback_outputs.pop("negative_add_time_ids", negative_add_time_ids)

                if i == len(timesteps) - 1 or ((i + 1) > num_warmup_steps and (i + 1) % self.scheduler.order == 0):
                    progress_bar.update()
                    if callback is not None and i % callback_steps == 0:
                        step_idx = i // getattr(self.scheduler, "order", 1)
                        callback(step_idx, t, latents)

        if not output_type == "latent":
            needs_upcasting = self.vae.dtype == torch.float16 and self.vae.config.force_upcast

            if needs_upcasting:
                self.upcast_vae()
                latents = latents.to(next(iter(self.vae.post_quant_conv.parameters())).dtype)

            image = self.vae.decode(latents / self.vae.config.scaling_factor, return_dict=False)[0]

            if needs_upcasting:
                self.vae.to(dtype=torch.float16)
        else:
            image = latents

        if not output_type == "latent":
            if self.watermark is not None:
                image = self.watermark.apply_watermark(image)

            image = self.image_processor.postprocess(image, output_type=output_type)

        self.maybe_free_model_hooks()

        if not return_dict:
            return (image,)

        return StableDiffusionXLPipelineOutput(images=image)


# ============================================================================
# 9. attention_utils (utils.attention_utils)
# ============================================================================
# NOTE: renamed to avoid collision with `show_mask` from generate_random_masks

def view_images(images: Union[np.ndarray, List],
                num_rows: int = 1,
                offset_ratio: float = 0.02,
                display_image: bool = True,
                downscale_rate=None) -> Image.Image:
    if type(images) is list:
        num_empty = len(images) % num_rows
    elif images.ndim == 4:
        num_empty = images.shape[0] % num_rows
    else:
        images = [images]
        num_empty = 0

    empty_images = np.ones(images[0].shape, dtype=np.uint8) * 255
    images = [image.astype(np.uint8) for image in images] + [empty_images] * num_empty
    num_items = len(images)

    h, w, c = images[0].shape
    offset = int(h * offset_ratio)
    num_cols = num_items // num_rows
    image_ = np.ones((h * num_rows + offset * (num_rows - 1),
                      w * num_cols + offset * (num_cols - 1), 3), dtype=np.uint8) * 255
    for i in range(num_rows):
        for j in range(num_cols):
            image_[i * (h + offset): i * (h + offset) + h:, j * (w + offset): j * (w + offset) + w] = images[
                i * num_cols + j]

    pil_img = Image.fromarray(image_)

    if downscale_rate:
        pil_img = pil_img.resize((int(pil_img.size[0] // downscale_rate), int(pil_img.size[1] // downscale_rate)))

    if display_image:
        display(pil_img)
    return pil_img


def show_image_relevance(image_relevance, image: Image.Image, relevnace_res=16):
    def show_cam_on_image(img, mask):
        heatmap = cv2.applyColorMap(np.uint8(255 * mask), cv2.COLORMAP_JET)
        heatmap = np.float32(heatmap) / 255
        cam = heatmap + np.float32(img)
        cam = cam / np.max(cam)
        return cam

    image = image.resize((relevnace_res ** 2, relevnace_res ** 2))
    image = np.array(image)

    image_relevance = image_relevance.reshape(1, 1, image_relevance.shape[-1], image_relevance.shape[-1])
    image_relevance = image_relevance.cuda()
    image_relevance = torch.nn.functional.interpolate(image_relevance, size=relevnace_res ** 2, mode='bilinear')
    image_relevance = image_relevance.cpu()
    image_relevance = (image_relevance - image_relevance.min()) / (image_relevance.max() - image_relevance.min())
    image_relevance = image_relevance.reshape(relevnace_res ** 2, relevnace_res ** 2)
    image = (image - image.min()) / (image.max() - image.min())
    vis = show_cam_on_image(image, image_relevance)
    vis = np.uint8(255 * vis)
    vis = cv2.cvtColor(np.array(vis), cv2.COLOR_RGB2BGR)
    return vis


def show_mask_attn(masks_list, out_images, tgt_size, display_image=True):
    """Original `show_mask` from attention_utils, renamed to avoid collision."""
    plt.figure(figsize=(5, 5))
    images = []

    for index_in_batch, masks in enumerate(masks_list):
        attn_image = masks[tgt_size].view(tgt_size, tgt_size).float()
        attn_image = show_image_relevance(attn_image, out_images[index_in_batch])
        attn_image = attn_image.astype(np.uint8)
        attn_image = np.array(Image.fromarray(attn_image).resize((tgt_size, tgt_size)))
        images.append(attn_image)

    images = view_images(np.stack(images, axis=0), display_image=False)

    if display_image:
        plt.imshow(images)
        plt.show()

    return images


def get_dynamic_threshold(tensor):
    return filters.threshold_otsu(tensor.cpu().numpy())


def attn_map_to_binary(attention_map, scaler=1.):
    attention_map_np = attention_map.cpu().numpy()
    threshold_value = filters.threshold_otsu(attention_map_np) * scaler
    binary_mask = (attention_map_np > threshold_value).astype(np.uint8)

    return binary_mask


def plot_object_attention_map(object_attention_map, output_dir, cross_attention_dim, i):
    object_attention_map_reshaped = object_attention_map.reshape(-1, 1).detach().cpu().numpy()
    plt.figure(figsize=(8, 8))
    plt.imshow(object_attention_map_reshaped.reshape(cross_attention_dim, cross_attention_dim), cmap='gray')
    plt.axis('off')
    plt.savefig(f"{output_dir}/object_attention_map_{i}.png", bbox_inches='tight')


def concat_images(images, size=512):
    width = height = size
    images = [ImageOps.fit(image, (size, size), Image.LANCZOS)
              for image in images]

    shape = (math.isqrt(len(images)), math.ceil(len(images) / math.isqrt(len(images))))
    image_size = (width * shape[1], height * shape[0])
    image = Image.new('RGB', image_size)

    for row in range(shape[0]):
        for col in range(shape[1]):
            offset = width * col, height * row
            idx = row * shape[1] + col
            image.paste(images[idx], offset)

    return image


# ============================================================================
# 10. postprocess (pipeline.mask_extraction.postprocess)
# ============================================================================

def calculate_ratio(convex_hull, image):
    hull_image = np.zeros_like(image)
    cv2.fillConvexPoly(hull_image, convex_hull, 255)
    overlap = cv2.bitwise_and(image, hull_image)
    overlap_area = np.sum(overlap > 0)
    hull_area = np.sum(hull_image > 0)
    return 1 - (overlap_area / hull_area)


def blob_merger(binary_mask):
    binary_mask = (binary_mask > 0).astype(np.uint8) * 255

    contours_data = cv2.findContours(binary_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if len(contours_data) == 3:
        _, contours, _ = contours_data
    else:
        contours, _ = contours_data

    filtered_contours = [cnt for cnt in contours if cnt.shape[0] >= 1]

    filtered_contours.sort(key=cv2.contourArea, reverse=True)

    union_image = np.zeros_like(binary_mask)
    main_blob = filtered_contours[0]
    merged = False

    cv2.drawContours(union_image, [main_blob], -1, (255), thickness=cv2.FILLED)

    for contour in filtered_contours[1:]:
        temp_image = np.copy(union_image)
        cv2.drawContours(temp_image, [contour], -1, (255), thickness=cv2.FILLED)
        combined_contour = np.vstack((main_blob, contour))
        convex_hull = cv2.convexHull(combined_contour)
        ratio = calculate_ratio(convex_hull, temp_image)
        if ratio <= 0.03:
            main_blob = combined_contour
            merged = True
            cv2.drawContours(union_image, [contour], -1, (255), thickness=cv2.FILLED)

    if merged:
        convex_hull = cv2.convexHull(main_blob)
        cv2.fillConvexPoly(union_image, convex_hull, (255))
    else:
        cv2.drawContours(union_image, [filtered_contours[0]], -1, (255), thickness=cv2.FILLED)

    return union_image


def apply_dilation(binary_mask, kernel_size=3):
    if isinstance(binary_mask, torch.Tensor):
        binary_mask = binary_mask.cpu().numpy()
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    dilated_mask = cv2.dilate(binary_mask.astype(np.uint8), kernel, iterations=1)
    return dilated_mask


def remove_intersections_from_largest(mask_outputs, buffer_size=3):
    num_masks = mask_outputs.size(0)
    mask_array = mask_outputs.view(num_masks, 32, 32)

    dilated_masks = torch.stack(
        [torch.from_numpy(apply_dilation(mask.numpy(), kernel_size=buffer_size)).to(mask_outputs.device) for mask in
         mask_array])

    for i in range(num_masks):
        for j in range(i + 1, num_masks):
            intersection = dilated_masks[i] & dilated_masks[j]
            if intersection.sum() > 0:
                area_i = mask_array[i].sum()
                area_j = mask_array[j].sum()

                if area_i > area_j:
                    mask_array[i][intersection.bool()] = 0
                else:
                    mask_array[j][intersection.bool()] = 0

    return mask_array.view(num_masks, 32, 32)


def run_postprocess(mask_outputs):
    mask_outputs = to_channels(mask_outputs)

    for m in range(mask_outputs.size(0)):
        try:
            merged_mask = blob_merger(mask_outputs[m, :].reshape(32, 32).numpy())
            merged_mask = merged_mask / 255
            mask_outputs[m, :, :] = torch.tensor(merged_mask, dtype=torch.int64)
        except:
            continue

    seperated_masks = remove_intersections_from_largest(mask_outputs).view(-1, 1024)
    combined_mask = from_channels(seperated_masks)

    return combined_mask


# ============================================================================
# 11. dbscan_mask_extract (pipeline.mask_extraction.dbscan_mask_extract)
# ============================================================================

def compute_pca(features, n_components=3, normalize=False):
    H, W, C = features.shape

    if normalize:
        features = (features - features.min()) / (features.max() - features.min())

    features = features.reshape(W * H, -1).cpu().numpy()
    pca = PCA(n_components=n_components)
    pca_featurs = pca.fit_transform(features)
    pca_featurs = pca_featurs.reshape(H, W, n_components)

    return pca_featurs


def show_pca(pca_features_list, titles=None, images_per_row=5):
    images_per_row = min(images_per_row, len(pca_features_list))

    titles = titles or ['Image'] * len(pca_features_list)
    num_features = len(pca_features_list)
    cmap = plt.get_cmap('inferno')

    images = []

    num_rows = (num_features + images_per_row - 1) // images_per_row

    fig, axes = plt.subplots(num_rows, images_per_row, figsize=(6 * images_per_row, 6 * num_rows), squeeze=False)

    for i, pca_features in enumerate(pca_features_list):
        normalized_pca_result = (pca_features - pca_features.min()) / (pca_features.max() - pca_features.min())
        images.append(Image.fromarray((normalized_pca_result * 255).astype(np.uint8)))

        row_idx, col_idx = divmod(i, images_per_row)

        ax = axes[row_idx, col_idx]
        ax.imshow(normalized_pca_result, cmap=cmap)
        ax.axis('off')

    for j in range(i + 1, num_rows * images_per_row):
        row_idx, col_idx = divmod(j, images_per_row)
        axes[row_idx, col_idx].axis('off')

    plt.tight_layout()
    plt.show()

    return images


def _set_seed_internal(seed: int):
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

    np.random.seed(seed)
    random.seed(seed)


def _read_yaml_internal(file_path):
    with open(file_path, "r") as yaml_file:
        yaml_data = yaml.safe_load(yaml_file)
    return yaml_data


def generate_latents(pipe, seed, device):
    _set_seed_internal(seed)
    g = torch.Generator().manual_seed(seed)
    shape = (1, pipe.unet.config.in_channels, 128, 128)
    latents = randn_tensor(shape, generator=g, device=device, dtype=torch.float16)

    return latents, g


def get_agg_self_attn(self_step_store, t, layers=None, cross_mask=None):
    if layers is None:
        layers = list(self_step_store[t].keys())

    self_attn_feats_mean = torch.cat([self_step_store[t][x] for x in layers]).mean(dim=0)

    if cross_mask is not None:
        self_attn_feats_mean[~cross_mask, :] = 0
        self_attn_feats_mean[:, ~cross_mask] = 0

    return self_attn_feats_mean


def db_scan(self_attn_feats_mean, eps=0.5, min_samples=5, metric='euclidean', algorithm='auto', min_cluster_size=10,
            display_image=True):
    X = self_attn_feats_mean.cpu().numpy()
    clustering = DBSCAN(eps=eps, min_samples=min_samples, metric=metric, algorithm=algorithm).fit(X)
    cluster_labels = clustering.labels_
    n_clusters = len(set(cluster_labels)) - (1 if -1 in clustering.labels_ else 0)

    small_clusters = [i for i in range(n_clusters) if (clustering.labels_ == i).sum() < min_cluster_size]

    for i in small_clusters:
        cluster_labels[clustering.labels_ == i] = -1
        n_clusters -= 1

    n_clusters = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)
    for i, cluster in enumerate(set(cluster_labels)):
        if cluster == -1:
            continue
        cluster_labels[cluster_labels == cluster] = i

    plt.imshow(cluster_labels.reshape(32, 32))
    plt.title(f'Clustering with DBSCAN')

    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    cluster_img = Image.open(buf).convert('RGB')

    if display_image:
        plt.show()
    else:
        plt.close()

    return cluster_labels, n_clusters, cluster_img


def save_pca_features_to_image(pca_features, filename):
    pca_features -= pca_features.min()
    pca_features /= pca_features.max()
    pca_features = (pca_features * 255).astype(np.uint8)

    img = Image.fromarray(pca_features)
    img.save(filename)


def generate_imgs_masks(pipe, prompt, seed, num_inference_steps, db_eps=0.1):
    latents, g = generate_latents(pipe, seed, pipe.device)

    out = pipe(prompt=[prompt],
               num_inference_steps=num_inference_steps,
               perform_counting=False,
               generator=g,
               latents=latents).images
    img = out[0]

    cross_map = torch.stack(
        [torch.cat(list(x.values())).mean(dim=0) for x in pipe.attention_store.cross_step_store.values()]).mean(dim=0)
    cross_map = cross_map[:, pipe.attention_store.object_token_idx]
    cross_mask = torch.from_numpy(attn_map_to_binary(cross_map, 1.)).to(cross_map.device).bool().view(-1)
    cross_mask_img = show_mask_attn([{32: cross_mask}], out, 32, display_image=False)
    self_attn_feats_mean = get_agg_self_attn(pipe.attention_store.self_step_store, 25, layers=['up_52'],
                                             cross_mask=cross_mask)

    self_attn_feats_mean = (self_attn_feats_mean + self_attn_feats_mean.T) / 2

    scores = []
    for eps in db_eps:
        np_clusters, n_dbscan_clusters, cluster_img = db_scan(self_attn_feats_mean, eps=eps, min_samples=10,
                                                              min_cluster_size=15,
                                                              metric='cosine', algorithm='auto', display_image=False)

        if n_dbscan_clusters > 1:
            shilluette_score = silhouette_score(self_attn_feats_mean.cpu().numpy(), np_clusters, metric='cosine')
        else:
            shilluette_score = 0

        scores.append(shilluette_score)

    best_eps = db_eps[np.argmax(scores)]
    np_clusters, n_dbscan_clusters, cluster_img = db_scan(self_attn_feats_mean, eps=best_eps, min_samples=10,
                                                          min_cluster_size=15,
                                                          metric='cosine', algorithm='auto', display_image=False)
    print(f'Best Epsilon: {best_eps}')

    size = (256, 256)
    cross_mask_img = cross_mask_img.resize(size)
    cluster_img = cluster_img.resize(size)
    return n_dbscan_clusters, img, cross_mask_img, cluster_img, np_clusters


def dbscan_extract_mask(prompt, pipe, config, seed):
    n_dbscan_clusters, img, cross_mask_img, cluster_img, np_clusters = generate_imgs_masks(pipe, prompt, seed,
                                                                                           config["counting_model"][
                                                                                               "num_inference_steps"],
                                                                                           db_eps=np.arange(0.1, 0.2,
                                                                                                            0.01))

    return np_clusters, n_dbscan_clusters, img


# ============================================================================
# 12. spatial_prior_predictor (pipeline.mask_extraction.spatial_prior_predictor)
# ============================================================================

def spatial_prior_predictor_undergeneration(input_mask, number_of_clusters_founded, desired_number_of_clusters, config,
                             in_channels=9, out_channels=10):
    gradual_padding = config["mask_creation"]["dbscan_mask"]["gradual_padding"]
    p = 0
    hub_dir = torch.hub.get_dir()
    repo_dir = f"{hub_dir}/mateuszbuda_brain-segmentation-pytorch_master"
    unet_model = torch.hub.load(repo_dir, 'unet',
                                in_channels=in_channels, out_channels=out_channels, init_features=128, pretrained=False,
                                source='local')

    checkpoint = torch.load(config["mask_creation"]["dbscan_mask"]["unet_checkpoint_path"],
                            map_location=torch.device(config['pipeline']['device']))
    unet_model.load_state_dict(checkpoint)
    unet_model.eval()
    input_mask = input_mask.unsqueeze(0)
    zeros = torch.zeros(input_mask.shape[0], in_channels - number_of_clusters_founded, input_mask.shape[2],
                        input_mask.shape[3])
    input_mask = torch.cat((input_mask, zeros), 1)

    padding = (p, p, p, p)
    input_mask = F.pad(input_mask, padding, mode='constant', value=0)

    with torch.no_grad():
        for i in range(desired_number_of_clusters - number_of_clusters_founded):

            if gradual_padding and (i % 2 == 0):
                p += 8
                input_mask = F.pad(input_mask, (p, p, p, p), mode='constant', value=0)

            output = unet_model(input_mask.float())
            binary_outputs = torch.where(output > 0.5, 1, 0)

            out_mask = binary_outputs.clone()
            out_mask[:, number_of_clusters_founded + i, :, :] = binary_outputs[:, -1, :, :]

            out_mask = out_mask.squeeze(0)
            for m in range(out_mask.size(0)):
                try:
                    merged_mask = blob_merger(out_mask[m, :].reshape(input_mask.size(-1), input_mask.size(-1)).numpy())
                    merged_mask = merged_mask / 255
                    out_mask[m, :, :] = torch.tensor(merged_mask, dtype=torch.int64)
                except:
                    continue

            out_mask = out_mask.unsqueeze(0)
            input_mask = out_mask[:, :in_channels, :, :]

    if gradual_padding:
        bbox = find_tight_bbox(out_mask)
        square_mask = make_square_crop(out_mask, bbox)
        square_mask_float = square_mask.float()
        resized_tensor = F.interpolate(square_mask_float, size=(32, 32), mode='nearest')
        binary_tensor = (resized_tensor > 0.5).int()
        out_mask = binary_tensor

    mask_outputs = out_mask[0, :desired_number_of_clusters].view(desired_number_of_clusters, -1)
    return mask_outputs


def spatial_prior_predictor_overgeneration(torch_object_masks, num_objects_to_remove):
    sum_per_channel = torch.sum(torch_object_masks, dim=(1, 2))

    _, indices = torch.sort(sum_per_channel, descending=True)
    indices = indices[:-num_objects_to_remove]

    return torch_object_masks[indices]


# ============================================================================
# 13. extract_mask (pipeline.mask_extraction.extract_mask)
# ============================================================================

def spatial_prior_predictor(sdxl_pipe, prompt, required_object_num, config, seed):
    obj_num_match = False

    vanilla_masks, n_dbscan_clusters, vanilla_img = dbscan_extract_mask(prompt, sdxl_pipe, config, seed)

    vanilla_masks, number_object_remain = remove_sparse_blobs(vanilla_masks)

    n_dbscan_clusters = number_object_remain

    vanilla_masks = torch.tensor(vanilla_masks, dtype=torch.float16).view(32, 32)
    vanilla_masks += 1

    if n_dbscan_clusters == 0:
        vanilla_masks[13:19, 13:19] = 1
        n_dbscan_clusters = 1

    if n_dbscan_clusters == required_object_num:
        correct_number_mask = vanilla_masks
        obj_num_match = True

    else:
        torch_object_masks = to_channels(vanilla_masks)

        if n_dbscan_clusters > required_object_num:
            object_masks = spatial_prior_predictor_overgeneration(torch_object_masks, n_dbscan_clusters - required_object_num)

        elif n_dbscan_clusters < required_object_num:
            object_masks = spatial_prior_predictor_undergeneration(torch_object_masks,
                                                    number_of_clusters_founded=n_dbscan_clusters,
                                                    desired_number_of_clusters=required_object_num, config=config)

        correct_number_mask = from_channels(object_masks)

    post_process_mask = run_postprocess(correct_number_mask)

    return vanilla_masks, correct_number_mask, post_process_mask, vanilla_img, obj_num_match


# ============================================================================
# 14. run_countright (pipeline.run_countright)
# ============================================================================

def read_yaml(file_path):
    with open(file_path, "r") as yaml_file:
        yaml_data = yaml.safe_load(yaml_file)
    return yaml_data


def set_seed(seed: int):
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

    np.random.seed(seed)
    random.seed(seed)


def init_sdxl_model(config):
    sdxl_pipe = SelfCountingSDXLPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0", use_safetensors=True,
        torch_dtype=torch.float16, variant="fp16", use_onnx=False
    )

    device = torch.device(config["pipeline"]["device"])
    sdxl_pipe.to(device)

    sdxl_pipe.counting_config = config['counting_model']

    if config['counting_model']['use_ddpm']:
        print('Using DDPM as scheduler.')
        sdxl_pipe.scheduler = diffusers.DDPMScheduler.from_config(sdxl_pipe.scheduler.config)

    return sdxl_pipe, device


def run_counting_pipeline_corrected_masks(sdxl_pipe, prompt, generator, object_masks, latents, config):
    out = sdxl_pipe(prompt=[prompt],
                    num_inference_steps=config["counting_model"]["num_inference_steps"],
                    perform_counting=True,
                    desired_mask=object_masks,
                    generator=generator,
                    latents=latents).images

    image = out[0]
    return image


def run_pipeline(prompt_objects, config, phase1_type, phase2_type):
    out_dir = config["pipeline"]["output_path"]
    os.makedirs(f'{out_dir}', exist_ok=True)

    metadata_json = []

    if os.path.isfile(f"{out_dir}/metadata.json"):
        with open(f"{out_dir}/metadata.json", "r") as f:
            metadata_json = json.load(f)

    sdxl_pipe, device = init_sdxl_model(config)

    for prompt_object in prompt_objects:
        prompt = prompt_object['prompt']
        seed = prompt_object['seed']

        set_seed(seed)
        generator = torch.Generator().manual_seed(seed)
        shape = (1, sdxl_pipe.unet.config.in_channels, 128, 128)
        latents = randn_tensor(shape, generator=generator, device=device, dtype=torch.float16)

        required_object_num = prompt_object['int_number']
        obj_name = prompt_object['object']

        if required_object_num > 9:
            print(f"Skipping {obj_name} with {required_object_num} objects as it is not supported.")
            continue

        img_id = f'{obj_name}_num={required_object_num}_seed={seed}'
        vanilla_img = None

        if phase1_type == 'random_mask':
            object_masks = generate_random_masks_factory(shape=config['mask_creation']['random_mask']['shape'],
                                                         number_clusters=required_object_num)
            show_mask(object_masks, f"{config['pipeline']['output_path']}/{img_id}_mask.png")
            obj_num_match = False
        elif phase1_type == 'dbscan_mask':
            vanilla_masks, correct_number_mask, object_masks, vanilla_img, obj_num_match = spatial_prior_predictor(sdxl_pipe, prompt,
                                                                                                    required_object_num,
                                                                                                    config, seed)
            show_mask_list([vanilla_masks, correct_number_mask, object_masks],
                           titles=[f'Vanilla mask: {int(vanilla_masks.max())}',
                                   f'Correct number mask: {int(correct_number_mask.max())}',
                                   f'Postprocess mask: {int(object_masks.max())}'],
                           save_path=f"{config['pipeline']['output_path']}/{img_id}_masks.png")
        elif phase1_type == 'no_mask':
            object_masks = None

        if obj_num_match:
            image = vanilla_img
        else:
            if phase2_type == 'ours_counting_loss':
                latents = apply_latent_partition(latents, object_masks)
                image = run_counting_pipeline_corrected_masks(sdxl_pipe, prompt, generator, object_masks, latents,
                                                              config)
            elif phase2_type == 'vanilla':
                pass

        image.save(f"{out_dir}/{img_id}.png")
        vanilla_img.save(f"{out_dir}/{img_id}_vanilla.png")

        metadata_item = {
            'id': img_id,
            'prompt': prompt,
            'seed': seed,
            'obj_class': obj_name,
            'requiered_object_num': required_object_num
        }

        metadata_json.append(metadata_item)

        with open(f"{out_dir}/metadata.json", "w") as f:
            json.dump(metadata_json, f, indent=4)


def parse_arguments():
    parser = argparse.ArgumentParser(description="config")
    parser.add_argument("--prompt", type=str, default="A photo of six kittens sitting on a branch")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--config", type=str, default="pipeline/pipeline_config.yaml")
    parser.add_argument("--dataset_file", type=str, default="")
    parser.add_argument("--output_path", type=str, default=None)

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_arguments()

    config = read_yaml(args.config)

    if args.output_path is not None:
        config["pipeline"]["output_path"] = args.output_path

    if (args.dataset_file is not None) and (len(args.dataset_file) > 0):
        with open(args.dataset_file, "r") as f:
            prompt_objects = json.load(f)[:]

    else:
        int_number, object_singular = find_nummod([args.prompt])[0]
        prompt_objects = [{
            "prompt": args.prompt,
            "object": object_singular,
            "int_number": word2number.get(int_number, 0),
            "seed": args.seed
        }, ]

    phase1_type = config['pipeline']['phase1_type']
    phase2_type = config['pipeline']['phase2_type']

    run_pipeline(prompt_objects, config, phase1_type, phase2_type)
